# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fd7d6fe812438dc00bd9ebaf8a4521b1"
name = "new checkout app"
handle = "new-checkout-app-19"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "checkout-extensibility-big.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
